// One act's branching map (docs/run-loop.md): a uniform per-act shape, seeded
// so a map is reproducible. `fight` draws the mob layer, `skirmish`/`elite` the
// recruitable pool, `boss` the Location's champion over mob escorts (run/encounters.ts).
// `battle` is generated by no map since 2026-09-13 (Titanspawn overhaul phase 3); the
// id survives for the tutorial's curated corridor and for a save that still holds one.

import { createRng, nextFloat, type RngState } from '../engine/rng/seededRng';
// Value import, but state.ts only takes `RunMap` back as a type — no runtime cycle.
import { FINALE_ACT } from './state';

/** Listed as a value, not just a union, so a loaded save can check a node type it read back (save.ts). */
export const MAP_NODE_TYPES = [
  'fight',
  'skirmish',
  'battle',
  'elite',
  'boss',
  'shop',
  'blacksmith',
  'equipmentReward',
  'ichorReward',
  'ichorDropReward',
  'manaWellReward',
  'passiveReward',
  'currencyReward',
  'forgeReward',
  'mentorReward',
  'tutorReward',
  'scribeReward',
  'event',
  // Act 6 only (docs/run-loop.md §4). `muster` is the Vigil, `finale` the Endbringer.
  'muster',
  'finale',
] as const;

export type MapNodeType = (typeof MAP_NODE_TYPES)[number];

export interface MapNode {
  id: string;
  type: MapNodeType;
  row: number;
  col: number;
  /** Next-row nodes reachable from this one. Empty only for the boss node. */
  nextIds: string[];
}

export interface RunMap {
  seed: number;
  nodes: Record<string, MapNode>;
  /** Row 0 = the single entry node, last row = the single boss node. */
  rows: string[][];
  startNodeIds: string[];
  bossNodeId: string;
}

// row 0 fight, 1/3/6 pick-1-of-3 rewards, 2 the spliced seat, 4 the Scribe, 5 elite-or-skirmish,
// 7 the funnel, 8 boss. Three fights an act since 2026-09-14 (per user direction): the un-forked
// Skirmish row came out to shorten the run without cutting an act, so the fork is the act's one
// Skirmish and every act 1-5 carries the spliced row — the shape is the same in all five. The
// Scribe row joined the same day (docs/mastery.md §3), ahead of the fork so the Evolution it buys
// is in hand for the previewed Elite and the Guardian.
const ROW_WIDTHS = [1, 3, 1, 3, 1, 2, 3, 1, 1] as const;

/**
 * Forced single-node row between the act's first two reward rows. Acts 1-3 it is the Mentor
 * (`mentorReward`, docs/growth-overhaul.md §11) — the ONLY place one appears, since it is absent
 * from REWARD_WEIGHTS — sitting ahead of the fork so the move is in hand for the act's first
 * recruitable fight. Act 4's is a forced Forge (2026-09-11, per user direction): a free slot at
 * about the time a third slot on the carry matters. Act 5's is a forced Tutor (2026-09-14, per
 * user direction): a guaranteed Late move going into the run's last Guardian, where it used to
 * be seated inside one of the act's reward rows.
 */
const SPLICED_ROW = 2;

/**
 * The Scribe (2026-09-14, per user direction, docs/mastery.md §3): a forced row every act 1-5
 * between the second reward row and the fork — pick two heroes, two Mastery pips each. It
 * cannot be concentrated, which is what keeps the forced beat from being "everything on the
 * carry" every act; the Scroll Cache in the reward pool and the Guild Hall shelf are where the
 * player prioritises. Absent from REWARD_WEIGHTS, so this row is its only seat.
 */
const SCRIBE_ROW = 4;

const LAST_MENTOR_ACT = 3;
const FORGE_ACT = 4;

/**
 * The Tutor (2026-09-07, per user direction): a guaranteed seat in act 4, taken INSIDE a
 * pick-1-of-3 reward row rather than given a forced row of its own. It is a lategame build
 * node — by act 4 a hero has a deep pool and four slots it is stuck with — so it is priced the
 * only way a reward row can price anything: against the two rolled rewards beside it. Absent
 * from REWARD_WEIGHTS, so this seat and act 5's spliced row are its only sources.
 */
const TUTOR_SEAT_ACTS: readonly number[] = [4];

function hasTutorSeat(actNumber: number): boolean {
  return TUTOR_SEAT_ACTS.includes(actNumber);
}

/** What the spliced row holds: the Mentor through LAST_MENTOR_ACT, the Forge in act 4, the Tutor after. */
function splicedRowType(actNumber: number): MapNodeType {
  if (actNumber <= LAST_MENTOR_ACT) return 'mentorReward';
  return actNumber === FORGE_ACT ? 'forgeReward' : 'tutorReward';
}

/**
 * The Blacksmith (2026-09-08, per user direction): from act 3 the funnel row widens to TWO, and
 * the act's one guaranteed spend becomes a fork — heroes and gear at the Guild Hall, or slots,
 * tiers and enchants at the Blacksmith. Acts 1-2 keep the single Guild Hall: the early roster is
 * still forming, and a fork that can cost a player their only recruit shelf wants a run with
 * some gold in it.
 */
const BLACKSMITH_FIRST_ACT = 3;

function hasBlacksmith(actNumber: number): boolean {
  return actNumber >= BLACKSMITH_FIRST_ACT;
}

function rowWidthsFor(actNumber: number): number[] {
  const widths = [...ROW_WIDTHS];
  if (hasBlacksmith(actNumber)) widths[widths.length - 2] = 2;
  return widths;
}

/** The pick-1-of-3 width. The Tutor only ever seats in a reward row this wide. */
const TUTOR_ROW_WIDTH = 3;

/** Reward-row pool. `mentorReward` and `tutorReward` are deliberately absent — each has its own forced seat. Weights are a first-pass balance. */
export const REWARD_WEIGHTS: readonly [MapNodeType, number][] = [
  // equipmentReward absorbs most of the frequency the three slot caches used to carry.
  ['equipmentReward', 40],
  // Ichor: two levels at par, aimed at ONE hero (run/ichor.ts) — the Scroll Cache's seat and
  // weight, re-pointed (docs/xp-overhaul.md §3). Weighted level with equipment: they are the
  // run's two growth axes, one per hero's numbers and one per hero's kit, and neither should be
  // the one you plan around. The supply is the only balance number and phase 6 sets it.
  ['ichorReward', 46],
  // The Boon: the part of the deleted relic pool that was actually worth having, handed to ONE
  // hero instead of all four. It is the only reward row node that changes how a hero plays
  // rather than how big its numbers are.
  ['passiveReward', 22],
  ['currencyReward', 20],
  // The Drop of Ichor: the same grant at half the size, and commoner for it.
  ['ichorDropReward', 14],
  // The Forge (+1 item slot) is permanent, compounds with every later drop, and is the only thing
  // here a hero can be at the cap for, so it stays the scarcest of the grants.
  //
  // 10 -> 38 (2026-09-08). When the nine heroes' authored second slot was removed, the roster lost
  // capacity rather than items, and measurement said so: paying the difficulty back through drop
  // odds alone recovered 0.8pp of the 3.9pp it cost, because a hero holding one item turns every
  // further drop into a sell. Slots are what was taken and slots are what is handed back. The node
  // is also no longer half-dead on arrival — nobody starts one Forge from the cap any more.
  ['forgeReward', 38],
  // FLAGGED FOR THE DESIGNER: 16 is an inference, not a decision — how often a run meets an event is a real tuning question.
  ['event', 16],
  // The Mana Well (2026-09-13, per user direction): +MANA_WELL_AMOUNT max Mana to one hero. The
  // one bare-number screen the constitution allows, because a pool is the stat that gates a
  // whole tier of moves — +30 Mana is a Late cast a fight, where +10 Attack was never visible.
  // Weighted with the purse: a top-up, not the axis you plan around.
  ['manaWellReward', 20],
];

/** Weighted sample WITHOUT replacement — a reward row never repeats a type. REWARD_WEIGHTS is wider than any row, so `count` is always satisfiable. */
function pickWeightedDistinct(
  rng: RngState,
  weights: readonly [MapNodeType, number][],
  count: number
): { values: MapNodeType[]; nextState: RngState } {
  const remaining = [...weights];
  const values: MapNodeType[] = [];
  let state = rng;
  while (values.length < Math.min(count, remaining.length)) {
    const total = remaining.reduce((sum, [, w]) => sum + w, 0);
    const { value: roll, nextState } = nextFloat(state);
    state = nextState;
    let threshold = roll * total;
    let index = remaining.length - 1;
    for (let i = 0; i < remaining.length; i++) {
      threshold -= remaining[i][1];
      if (threshold <= 0) {
        index = i;
        break;
      }
    }
    values.push(remaining[index][0]);
    remaining.splice(index, 1);
  }
  return { values, nextState: state };
}

function nodeId(row: number, col: number): string {
  return `r${row}-c${col}`;
}

/**
 * Act 6 is a corridor, not a map (docs/run-loop.md §4): the Vigil, then the Endbringer.
 * No branch and no RNG — the seed is kept only so a RunMap stays reproducible from it.
 */
function finaleMap(seed: number): RunMap {
  const musterId = nodeId(0, 0);
  const finaleId = nodeId(1, 0);
  return {
    seed,
    nodes: {
      [musterId]: { id: musterId, type: 'muster', row: 0, col: 0, nextIds: [finaleId] },
      [finaleId]: { id: finaleId, type: 'finale', row: 1, col: 0, nextIds: [] },
    },
    rows: [[musterId], [finaleId]],
    startNodeIds: [musterId],
    bossNodeId: finaleId,
  };
}

/**
 * Rows top-down (types first), forward edges within a column window, then a
 * repair pass so every node has an incoming edge.
 */
export function generateMap(seed: number, actNumber: number = 1): RunMap {
  if (actNumber >= FINALE_ACT) return finaleMap(seed);
  const rowWidths = rowWidthsFor(actNumber);
  const bossRow = rowWidths.length - 1;
  const funnelRow = bossRow - 1;
  // A pick-1-of-3 reward row sits between the Elite/Skirmish choice and the funnel, so the Elite
  // row is two up from the funnel rather than one.
  const eliteRow = funnelRow - 2;

  function isRewardRow(row: number): boolean {
    return row !== 0 && row !== SPLICED_ROW && row !== SCRIBE_ROW && row !== eliteRow && row !== funnelRow && row !== bossRow;
  }

  function fixedNodeType(row: number, col: number): MapNodeType {
    if (row === 0) return 'fight';
    if (row === SPLICED_ROW) return splicedRowType(actNumber);
    if (row === SCRIBE_ROW) return 'scribeReward';
    // Elite-or-Skirmish since 2026-09-13 — both hero pool, both recruitable, and the two
    // preview their typing on the tile (run/encounters.ts guarantees they differ in a type).
    if (row === eliteRow) return col === 0 ? 'elite' : 'skirmish';
    if (row === funnelRow) return col === 0 ? 'shop' : 'blacksmith';
    return 'boss';
  }

  let rng = createRng(seed);

  // The Tutor's seat is rolled BEFORE any row is generated, so its two draws sit at a fixed
  // point in the seeded stream — a map has to stay reproducible from its seed alone.
  let tutorRow = -1;
  let tutorCol = -1;
  if (hasTutorSeat(actNumber)) {
    const seats: number[] = [];
    for (let row = 0; row < rowWidths.length; row++) {
      if (isRewardRow(row) && rowWidths[row] === TUTOR_ROW_WIDTH) seats.push(row);
    }
    if (seats.length > 0) {
      const { value: rowRoll, nextState: s1 } = nextFloat(rng);
      rng = s1;
      const { value: colRoll, nextState: s2 } = nextFloat(rng);
      rng = s2;
      tutorRow = seats[Math.floor(rowRoll * seats.length)];
      tutorCol = Math.floor(colRoll * rowWidths[tutorRow]);
    }
  }

  const nodes: Record<string, MapNode> = {};
  const rows: string[][] = [];

  for (let row = 0; row < rowWidths.length; row++) {
    const rowIds: string[] = [];
    // Reward rows roll a whole row at once (distinct sample); fixed rows never touch the RNG.
    const rewardRow = isRewardRow(row);
    let rewardTypes: MapNodeType[] = [];
    if (rewardRow) {
      // A Tutor row rolls one fewer reward and the Tutor takes the freed seat rather than
      // overwriting a rolled one — the row still offers three distinct things.
      const forced = row === tutorRow ? 1 : 0;
      const picked = pickWeightedDistinct(rng, REWARD_WEIGHTS, rowWidths[row] - forced);
      rewardTypes = picked.values;
      rng = picked.nextState;
      if (forced) rewardTypes.splice(tutorCol, 0, 'tutorReward');
    }
    for (let col = 0; col < rowWidths[row]; col++) {
      const type = rewardRow ? rewardTypes[col] : fixedNodeType(row, col);
      const id = nodeId(row, col);
      nodes[id] = { id, type, row, col, nextIds: [] };
      rowIds.push(id);
    }
    rows.push(rowIds);
  }

  for (let row = 0; row < rowWidths.length - 1; row++) {
    const from = rows[row];
    const to = rows[row + 1];

    // The two forks every path arrives at holding BOTH options.
    //
    // The funnel has always been one: from act 3 it is a Guild Hall/Blacksmith choice, and it is
    // the act's ONLY guaranteed spend, so a map that decided it would be deciding the run.
    //
    // Elite-or-Battle joined it on 2026-09-08 (per user direction). It used to STEER — the reward
    // row above it sent left to the Elite, right to the Battle and middle to both — which priced
    // the choice rather than removing it, and read correctly while the whole act was on screen to
    // be read. It does not survive the map becoming a scene: with only the row in front of you
    // visible, a reward two steps back quietly closing an encounter is a rule the player is asked
    // to hold in their head rather than see. The choice is now simply always there.
    if ((row + 1 === funnelRow || row + 1 === eliteRow) && to.length > 1) {
      for (const fromId of from) nodes[fromId].nextIds = [...to];
      continue;
    }

    for (const fromId of from) {
      // Clamp into the TARGET row's width first, or a narrow `to` yields an empty window and strands the node.
      const targetCol = Math.min(nodes[fromId].col, to.length - 1);
      const windowLo = Math.max(0, targetCol - 1);
      const windowHi = Math.min(to.length - 1, targetCol + 1);
      const candidates = to.slice(windowLo, windowHi + 1);

      const { value: edgeRoll, nextState: s1 } = nextFloat(rng);
      rng = s1;
      const edgeCount = candidates.length > 1 && edgeRoll < 0.4 ? 2 : 1;

      const picked = new Set<string>();
      while (picked.size < Math.min(edgeCount, candidates.length)) {
        const { value: idx, nextState: s2 } = nextFloat(rng);
        rng = s2;
        picked.add(candidates[Math.floor(idx * candidates.length)]);
      }
      nodes[fromId].nextIds = [...picked];
    }

    // Repair pass: every node in the next row gets an incoming edge.
    const reached = new Set(from.flatMap((id) => nodes[id].nextIds));
    for (const toId of to) {
      if (reached.has(toId)) continue;
      const toCol = nodes[toId].col;
      let nearest = from[0];
      let bestDist = Infinity;
      for (const fromId of from) {
        const dist = Math.abs(nodes[fromId].col - toCol);
        if (dist < bestDist) {
          bestDist = dist;
          nearest = fromId;
        }
      }
      nodes[nearest].nextIds.push(toId);
    }
  }

  return {
    seed,
    nodes,
    rows,
    startNodeIds: rows[0],
    bossNodeId: rows[bossRow][0],
  };
}
