// One act's branching map (docs/run-loop.md): a uniform per-act shape, seeded
// so a map is reproducible. `fight` draws the mob layer, `skirmish`/`elite` the
// recruitable pool, `boss` the Location's champion over mob escorts (run/encounters.ts).
// `battle` is generated by no map since 2026-09-13 (Titanspawn overhaul phase 3); the
// id survives for a save that still holds one.

import { createRng, nextFloat, type RngState } from '../engine/rng/seededRng';
// Value import, but state.ts only takes `RunMap` back as a type — no runtime cycle.
import { FINALE_ACT } from './state';

/** Listed as a value, not just a union, so a loaded save can check a node type it read back (save.ts). */
export const MAP_NODE_TYPES = [
  'fight',
  'skirmish',
  'battle',
  'elite',
  'boss',
  'shop',
  'equipmentReward',
  'scrollReward',
  'manaWellReward',
  'forgeReward',
  'leyLineReward',
  'restReward',
  'passiveReward',
  'currencyReward',
  'mentorReward',
  'tutorReward',
  'scribeReward',
  'event',
  // Act 6 only (docs/run-loop.md §4). `muster` is the Vigil, `finale` the Herald and, behind it
  // in the same fight, the Titan's Eyes (docs/titan-eyes.md §10).
  'muster',
  'finale',
] as const;

export type MapNodeType = (typeof MAP_NODE_TYPES)[number];

export interface MapNode {
  id: string;
  type: MapNodeType;
  row: number;
  col: number;
  /** Next-row nodes reachable from this one. Empty only for the boss node. */
  nextIds: string[];
}

export interface RunMap {
  seed: number;
  nodes: Record<string, MapNode>;
  /** Row 0 = the single entry node, last row = the single boss node. */
  rows: string[][];
  startNodeIds: string[];
  bossNodeId: string;
}

// row 0 fight, 1/3/6 pick-1-of-3 rewards, 2 the spliced seat, 4 the Scribe, 5 elite-or-skirmish,
// 7 the funnel, 8 boss. Three fights an act since 2026-09-14 (per user direction): the un-forked
// Skirmish row came out to shorten the run without cutting an act, so the fork is the act's one
// Skirmish and every act 1-5 carries the spliced row — the shape is the same in all five. The
// Scribe row joined the same day (docs/mastery.md §3), ahead of the fork so the Evolution it buys
// is in hand for the previewed Elite and the Guardian.
const ROW_WIDTHS = [1, 3, 1, 3, 1, 2, 3, 1, 1] as const;

/**
 * Forced single-node row between the act's first two reward rows. Acts 1-3 it is the Mentor
 * (`mentorReward`, docs/growth-overhaul.md §11) — the ONLY place one appears, since it is absent
 * from REWARD_WEIGHTS — sitting ahead of the fork so the move is in hand for the act's first
 * recruitable fight. Acts 4 and 5 are a forced Tutor: a guaranteed Late move an act, ahead of
 * the two Guardians it matters most against. Act 4's used to be the Forge (2026-09-11), deleted
 * with item slots (docs/gear-absorption.md §4), and the Tutor that took its place used to be
 * seated inside one of act 4's reward rows.
 */
const SPLICED_ROW = 2;

/**
 * The Scribe (2026-09-14, per user direction, docs/mastery.md §3): a forced row every act 1-5
 * between the second reward row and the fork — pick two heroes, two Mastery pips each. It
 * cannot be concentrated, which is what keeps the forced beat from being "everything on the
 * carry" every act; the Scroll Cache in the reward pool and the Guild Hall shelf are where the
 * player prioritises. Absent from REWARD_WEIGHTS, so this row is its only seat.
 */
const SCRIBE_ROW = 4;

const LAST_MENTOR_ACT = 3;

/** What the spliced row holds: the Mentor through LAST_MENTOR_ACT, the Tutor after. */
function splicedRowType(actNumber: number): MapNodeType {
  return actNumber <= LAST_MENTOR_ACT ? 'mentorReward' : 'tutorReward';
}

/** Every act's rows are the same width: the funnel is one Guild Hall, forced (docs/gear-absorption.md §6). */
function rowWidthsFor(actNumber: number): number[] {
  void actNumber;
  return [...ROW_WIDTHS];
}

/** Reward-row pool. `mentorReward` and `tutorReward` are deliberately absent — each has its own forced seat. Weights are a first-pass balance. */
export const REWARD_WEIGHTS: readonly [MapNodeType, number][] = [
  // The Equipment Cache: the deliberate gear faucet, where the player picks a family (docs/
  // gear-absorption.md §5). 40 + the Forge's 38 since 2026-09-15 — the Forge's seat came to the
  // Cache rather than vanishing, so every other reward keeps the frequency it had.
  ['equipmentReward', 78],
  // The Scroll Cache: SCROLL_CACHE_COUNT Mastery pips, divided as the player likes (run/mastery.ts,
  // docs/mastery.md §3) — the seat and weight it held before Ichor took them (2026-09-14, Mastery
  // phase 2). Weighted level with equipment: they are the run's two growth axes, one per hero's
  // form and one per hero's kit, and neither should be the one you plan around. The supply is the
  // only balance number and phase 5 sets it; the Drop's seat (14) retired with Ichor and was not
  // re-pointed. 46 → 20 on 2026-09-17 (per user direction): at 46 an act held two or more Caches
  // 47% of the time, and with the Scribe's 2 a single Cache is an Evolution, so early Evolutions
  // were the default; at 20 it is one act in six, all three rows one in fifty, and an act still
  // holds one more often than not (60%).
  ['scrollReward', 20],
  // The Boon: the part of the deleted relic pool that was actually worth having, handed to ONE
  // hero instead of all four. It is the only reward row node that changes how a hero plays
  // rather than how big its numbers are.
  ['passiveReward', 22],
  ['currencyReward', 20],
  // FLAGGED FOR THE DESIGNER: 16 is an inference, not a decision — how often a run meets an event is a real tuning question.
  ['event', 16],
  // The Mana Well (2026-09-13, per user direction): +MANA_WELL_AMOUNT max Mana to one hero. The
  // one bare-number screen the constitution allows, because a pool is the stat that gates a
  // whole tier of moves — +30 Mana is a Late cast a fight, where +10 Attack was never visible.
  // Weighted with the purse: a top-up, not the axis you plan around.
  ['manaWellReward', 20],
  // The Rest (2026-09-15, per user direction, docs/run-loop.md "Wounds"): the roster made whole,
  // priced the only way a reward row prices anything — against the two rewards beside it. Weighted
  // so it is usually somewhere in an act and never in every row; the walk floor and the Guild
  // Hall's mend are the other two answers to a wound, and this is the one that costs power.
  ['restReward', 30],
  // The Forge and the Ley Line (2026-09-17, per user direction): the Smithy's two verbs, the
  // Anvil's and the Enchanter's, each given a free seat on the map — one lift of one worn piece,
  // one hero drawing LEY_LINE_FORCE of its own element's Force for the run. Weighted level with
  // each other, under Rest and over the Cache: neither is the axis you plan around. Nine types into nine
  // seats an act is what makes a reward row a draw again; seven into nine showed every type every
  // act (docs/run-loop.md "The Forge and the Ley Line").
  ['forgeReward', 25],
  ['leyLineReward', 25],
];

/** Weighted sample WITHOUT replacement — a reward row never repeats a type. REWARD_WEIGHTS is wider than any row, so `count` is always satisfiable. */
function pickWeightedDistinct(
  rng: RngState,
  weights: readonly [MapNodeType, number][],
  count: number
): { values: MapNodeType[]; nextState: RngState } {
  const remaining = [...weights];
  const values: MapNodeType[] = [];
  let state = rng;
  while (values.length < Math.min(count, remaining.length)) {
    const total = remaining.reduce((sum, [, w]) => sum + w, 0);
    const { value: roll, nextState } = nextFloat(state);
    state = nextState;
    let threshold = roll * total;
    let index = remaining.length - 1;
    for (let i = 0; i < remaining.length; i++) {
      threshold -= remaining[i][1];
      if (threshold <= 0) {
        index = i;
        break;
      }
    }
    values.push(remaining[index][0]);
    remaining.splice(index, 1);
  }
  return { values, nextState: state };
}

function nodeId(row: number, col: number): string {
  return `r${row}-c${col}`;
}

/**
 * Act 6 is a corridor, not a map (docs/run-loop.md §4): the Vigil, then the one fight — the
 * Herald, and the Titan's Eyes once it falls (docs/titan-eyes.md §10). No branch and no RNG —
 * the seed is kept only so a RunMap stays reproducible from it.
 */
function finaleMap(seed: number): RunMap {
  const musterId = nodeId(0, 0);
  const finaleId = nodeId(1, 0);
  return {
    seed,
    nodes: {
      [musterId]: { id: musterId, type: 'muster', row: 0, col: 0, nextIds: [finaleId] },
      [finaleId]: { id: finaleId, type: 'finale', row: 1, col: 0, nextIds: [] },
    },
    rows: [[musterId], [finaleId]],
    startNodeIds: [musterId],
    bossNodeId: finaleId,
  };
}

/**
 * Rows top-down (types first), forward edges within a column window, then a
 * repair pass so every node has an incoming edge.
 */
export function generateMap(seed: number, actNumber: number = 1): RunMap {
  if (actNumber >= FINALE_ACT) return finaleMap(seed);
  const rowWidths = rowWidthsFor(actNumber);
  const bossRow = rowWidths.length - 1;
  const funnelRow = bossRow - 1;
  // A pick-1-of-3 reward row sits between the Elite/Skirmish choice and the funnel, so the Elite
  // row is two up from the funnel rather than one.
  const eliteRow = funnelRow - 2;

  function isRewardRow(row: number): boolean {
    return row !== 0 && row !== SPLICED_ROW && row !== SCRIBE_ROW && row !== eliteRow && row !== funnelRow && row !== bossRow;
  }

  function fixedNodeType(row: number, col: number): MapNodeType {
    if (row === 0) return 'fight';
    if (row === SPLICED_ROW) return splicedRowType(actNumber);
    if (row === SCRIBE_ROW) return 'scribeReward';
    // Elite-or-Skirmish since 2026-09-13 — both hero pool, both recruitable, and the two
    // preview their typing on the tile (run/encounters.ts guarantees they differ in a type).
    if (row === eliteRow) return col === 0 ? 'elite' : 'skirmish';
    if (row === funnelRow) return 'shop';
    return 'boss';
  }

  let rng = createRng(seed);

  const nodes: Record<string, MapNode> = {};
  const rows: string[][] = [];

  for (let row = 0; row < rowWidths.length; row++) {
    const rowIds: string[] = [];
    // Reward rows roll a whole row at once (distinct sample); fixed rows never touch the RNG.
    const rewardRow = isRewardRow(row);
    let rewardTypes: MapNodeType[] = [];
    if (rewardRow) {
      const picked = pickWeightedDistinct(rng, REWARD_WEIGHTS, rowWidths[row]);
      rewardTypes = picked.values;
      rng = picked.nextState;
    }
    for (let col = 0; col < rowWidths[row]; col++) {
      const type = rewardRow ? rewardTypes[col] : fixedNodeType(row, col);
      const id = nodeId(row, col);
      nodes[id] = { id, type, row, col, nextIds: [] };
      rowIds.push(id);
    }
    rows.push(rowIds);
  }

  for (let row = 0; row < rowWidths.length - 1; row++) {
    const from = rows[row];
    const to = rows[row + 1];

    // The two forks every path arrives at holding BOTH options.
    //
    // The funnel has always been one: from act 3 it is a Guild Hall/Blacksmith choice, and it is
    // the act's ONLY guaranteed spend, so a map that decided it would be deciding the run.
    //
    // Elite-or-Battle joined it on 2026-09-08 (per user direction). It used to STEER — the reward
    // row above it sent left to the Elite, right to the Battle and middle to both — which priced
    // the choice rather than removing it, and read correctly while the whole act was on screen to
    // be read. It does not survive the map becoming a scene: with only the row in front of you
    // visible, a reward two steps back quietly closing an encounter is a rule the player is asked
    // to hold in their head rather than see. The choice is now simply always there.
    if ((row + 1 === funnelRow || row + 1 === eliteRow) && to.length > 1) {
      for (const fromId of from) nodes[fromId].nextIds = [...to];
      continue;
    }

    for (const fromId of from) {
      // Clamp into the TARGET row's width first, or a narrow `to` yields an empty window and strands the node.
      const targetCol = Math.min(nodes[fromId].col, to.length - 1);
      const windowLo = Math.max(0, targetCol - 1);
      const windowHi = Math.min(to.length - 1, targetCol + 1);
      const candidates = to.slice(windowLo, windowHi + 1);

      const { value: edgeRoll, nextState: s1 } = nextFloat(rng);
      rng = s1;
      const edgeCount = candidates.length > 1 && edgeRoll < 0.4 ? 2 : 1;

      const picked = new Set<string>();
      while (picked.size < Math.min(edgeCount, candidates.length)) {
        const { value: idx, nextState: s2 } = nextFloat(rng);
        rng = s2;
        picked.add(candidates[Math.floor(idx * candidates.length)]);
      }
      nodes[fromId].nextIds = [...picked];
    }

    // Repair pass: every node in the next row gets an incoming edge.
    const reached = new Set(from.flatMap((id) => nodes[id].nextIds));
    for (const toId of to) {
      if (reached.has(toId)) continue;
      const toCol = nodes[toId].col;
      let nearest = from[0];
      let bestDist = Infinity;
      for (const fromId of from) {
        const dist = Math.abs(nodes[fromId].col - toCol);
        if (dist < bestDist) {
          bestDist = dist;
          nearest = fromId;
        }
      }
      nodes[nearest].nextIds.push(toId);
    }
  }

  return {
    seed,
    nodes,
    rows,
    startNodeIds: rows[0],
    bossNodeId: rows[bossRow][0],
  };
}
